In [ ]:

pip install numpy
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.
[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
import numpy
print(numpy.__version__)
2.0.1
import numpy as np
a = np.array
print(a)
<built-in function array>
#Defining an array
a = np.array([1,2,3])
print(a)
[1 2 3]
a = np.array([1,2,3])
print(a.dtype)
print(type(a))
print(a.ndim)
int64
<class 'numpy.ndarray'>
1
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.dtype)
print(type(a))
print(a.ndim)
[[1 2 3]
 [4 5 6]]
int64
<class 'numpy.ndarray'>
2
#Defining Complex numbers
a = np.array([1,2,3], complex)
print(a)
[1.+0.j 2.+0.j 3.+0.j]
#Printing size and shape
a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)
6
(1, 6)
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)
#Reshape - Change of rows and columns
a = np.array([[1,2],[3,4],[5,6]])
print('Original array')
print(a)

a = a.reshape(2,3)
print('Reshaped array')
print(a)
#Accessing of elements
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print(a[0,1])
print(a[2,1])
#Basic functions like min,max ans sum in 1D-array
a = np.array([1,2,3,50,4,45,4])
print(a)
print('Maximum number: ', a.max())
print('Minimum number: ', a.min())
print('Sum of all values: ', a.sum())
np.identity(3)
b = np.zeros((2,4))
print(b)
b = np.ones((2,4))
print(b)
a = np.array([[1,2],[3,4],[5,6]])
print(a) 
#Basic functions like min,max ans sum in 2D-array
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("Max number in column:", a.max(axis=0))
print('Min number in row:',a.min(axis=1))
print('Sum of all values in rows:',a.sum(axis=1))
# randn --> generates random number between (-1,0,1)

a = np.random.randn(5,3)
print(a)
# Arithmetic operation
    #Addition
    #Subtraction
    #Multiplication
    #Division
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[10,5,15]])

print("Sum of a and b:\n ", a+b)
print('*********************************')
print("Sub of a and b:\n ", a-b)
print('*********************************')
print("Product of a and b:\n", a*b)
print('*********************************')
print("division of a and b: \n", a/b)
#Ranging function ---> range()

for i in range(11):
    print(i, end=' ')
# Ranging function in numpy --> arange()

print(np.arange(12))
print(np.arange(12).reshape(3,4))
arr = np.arange(12).reshape(2,2,3) # --> 2*3, 2*3 (generates 2 matrices)
print(arr)
print('*********************************')
print(arr[0])
print('*********************************')
print(arr[1])
print('*********************************')
print(arr[0][1])
print('*********************************')
print(arr[0][1][2])
#slicing with arange()
print(np.arange(12))
print(np.arange(12)[0:7])
print(np.arange(12)[0:7][1])
log = np.logspace(10,20, num = 5)
print(log)
arr = np.linspace(10,20,5)
print(arr)
Numpy Broadcasting
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b
print(c)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([2,4,6,8])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a+b)
print('*********************************')
print(a-b)
print('*********************************')
print(a*b)
arr1 = np.arange(15).reshape(5,3)
print(arr1)
print('*********************************')
arr2 = np.arange(5).reshape(5,1)
print(arr2)
print('*********************************')
print(arr1 + arr2)
print(np.array(['apple','banana','cherry']))
print('*********************************')
print(np.array([['welcome'],['hi']]))
print(np.char.add(['welcome'],['hi']))
arr = np.array(["A","B","C"])
result = np.char.multiply(arr,3)
print(result)
# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.86745678])
print(arr)
print("Rounding function: ", np.around(arr))
print('*********************************')
print("With decimal:",np.around(arr, 2) )
arr = np.array([12.2, 90.12, 12.54, 52.85])
print("Floor: ", np.floor(arr))
print("Ceil: ", np.ceil(arr))
# Mean, Median, Average

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
print(np.median(a))
print('*********************************')
print(np.median(a,0)) #--> axis = columns
print('*********************************')
print(np.median(a,1)) # --> axis = rows
print('*********************************')
print(np.mean(a))
print('*********************************')
print(np.average(a))
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)
a = np.array([[100,200],[30,40]])
b = np.array([[10,20],[50,60]])
print(a)
print('*********************************')
print(b)
print('*********************************')
print(a*b) # --> Multiplication
print('*********************************')
x = np.dot(a,b) # --> Dot product
print(x)
 
 
 